DevTools 01/02 (Ложкин Александр, Ш20-191-1)
OblivionSorcerer/DevTools_lab01 pull request #2
Opened 2022-11-24 21:10 UTC by OblivionSorcerer

Выполнил все требования второй части первой лабораторной работы:
Написал Интеграционные и Приемочные тесты, доработал связку "категория-продукты" .
Немного поэкспериментировал со стилями отображения списка товаров (на функциональность не влияет)

2022-11-26 16:44 UTC, MihailRomanov requested changes
Замечания примерно одинаковые. Не стал расписывать всё - пройдитесь по остальным методам и проверьте сами.
Детали в чате

2022-11-26 16:44 UTC, MihailRomanov commented on NorthwindApp/Northwind.Web.Tests/AcceptanceTesting.cs
> +            "Trusted_Connection=True;MultipleActiveResultSets=true").Options);
По поводу использования базы в приемочных тестах я расписал в чате.

2022-11-26 16:44 UTC, MihailRomanov commented on NorthwindApp/Northwind.Web.Tests/AcceptanceTesting.cs
> +            links.Count().Should().Be(2);
Опять же мы говорили, что в приемочных мы используем исключительно Read-Only проверки. 
Да, когда-то могут быть допустимы и такие, но тогда это приемка, идущая не на продакшен окружении.

2022-11-26 16:44 UTC, MihailRomanov commented on NorthwindApp/Northwind.Web.Tests/CategoriesControllerIntegrationTesting.cs
> +            response.Headers.Location.Should().BeNull();
А ошибку на странице проверить?

2022-11-26 16:44 UTC, MihailRomanov commented on NorthwindApp/Northwind.Web.Tests/CategoriesControllerIntegrationTesting.cs
> +            response.StatusCode.Should().Be(System.Net.HttpStatusCode.OK);
А что бы сразу не проверить, что мы не просто перешли на детальную страницу, но и данные на ней какие и должны быть?

2022-11-26 16:44 UTC, MihailRomanov commented on NorthwindApp/Northwind.Web.Tests/CategoriesControllerIntegrationTesting.cs
> +            context.Categories.First().Should().BeEquivalentTo(category);
И снова - как пользователь поймет, что что-то пошло не так (а мы проверим, что мы это ему сообщаем)

2022-12-02 18:49 UTC, OblivionSorcerer commented
Были исправлены недочеты:
* БД больше не используется в приемочных тестах, а используется отдельный класс .
* Проверяются данные при переходе на страницы (Details, Edit, Delete)
* Добавлена проверка наличия ошибок

2022-12-03 06:26 UTC, OblivionSorcerer commented on NorthwindApp/Northwind.Web.Tests/AcceptanceTesting.cs
> +            "Trusted_Connection=True;MultipleActiveResultSets=true").Options);
Исправил

2022-12-03 06:27 UTC, OblivionSorcerer commented on NorthwindApp/Northwind.Web.Tests/CategoriesControllerIntegrationTesting.cs
> +            response.StatusCode.Should().Be(System.Net.HttpStatusCode.OK);
Ошибка теперь проверяется

2022-12-03 06:36 UTC, MihailRomanov approved these changes

2022-12-03 08:45 UTC, merged